export interface CaseStudy {
  slug: string;
  industry: string;
  industryEmoji: string;
  stat: string;
  title: string;
  avatar: string;
  name: string;
  role: string;
  htmlContent?: string;
}

export const caseStudies: CaseStudy[] = [
  {
    slug: 'ai-built-website',
    industry: 'AI / Technology',
    industryEmoji: '🤖',
    stat: '$40,000+ saved. Built in hours from a Slack channel.',
    title: 'We built our entire brand identity and production website — guidelines, copy, design, SEO — using our own AI agent. No designers. No agencies. No templates.',
    avatar: 'PA',
    name: 'Páramo AI',
    role: 'paramo.sh',
  },
  {
    slug: 'seo-automation',
    industry: 'SEO / Digital Marketing',
    industryEmoji: '📈',
    stat: '$2,500+/month saved. Fully automated. Zero agencies.',
    title: 'We automated our entire SEO and programmatic SEO strategy — keyword research, content calendars, city pages, competitor analysis — for paramo.sh and sister brand getclawhelp.com using our AI agent.',
    avatar: 'PA',
    name: 'Páramo AI',
    role: 'getclawhelp.com',
  },
  {
    slug: 'skilletz-cafe',
    industry: 'Restaurant / Food & Beverage',
    industryEmoji: '🍳',
    stat: '5 automations. One small team. Running like 50 people.',
    title: 'A family-run breakfast diner deployed AI to orchestrate marketing, dispute resolution, school partnerships, and custom analytics — without hiring a single person.',
    avatar: 'SC',
    name: "Skillet'z Cafe",
    role: 'Fremont, California',
  },
  {
    slug: 'real-estate-portfolio',
    industry: 'Real Estate / Property Management',
    industryEmoji: '🏠',
    stat: 'From scattered properties to a command center.',
    title: 'A real estate investor managing properties across multiple markets built an AI system for deal sourcing, tax optimization, and family financial education.',
    avatar: 'RE',
    name: 'Bay Area Investor',
    role: 'San Francisco Bay Area',
  },
  {
    slug: 'bookkeeping-automation',
    industry: 'Finance / Bookkeeping',
    industryEmoji: '💰',
    stat: '8 hours a month. Thousands in missed deductions. Fixed by AI.',
    title: 'A small business owner running multiple entities eliminated bookkeeping chaos — and discovered thousands in tax deductions their software was missing.',
    avatar: 'SB',
    name: 'Small Business Owner',
    role: 'Minneapolis, MN',
  },
  {
    slug: 'employee-training-sops',
    industry: 'Home Services / Operations',
    industryEmoji: '🏢',
    stat: '30 employees. Zero written procedures. Until now.',
    title: 'A growing home services company turned tribal knowledge into a living operating manual — handbooks, SOPs, and training guides generated by AI in days, not months.',
    avatar: 'HS',
    name: 'Home Services Company',
    role: 'Austin, Texas',
  },
];
